services:
  nginx:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  nginx-cf-tunnel:
    container_name: nginx-cf-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${NGINX_CF_TUNNEL_TOKEN}
    restart: unless-stopped
    network_mode: host
    profiles:
      - cloudflare
